apiVersion: v1
kind: Service
metadata:
  name: jenkins-lb-service
  namespace: jenkins

spec:
  type: LoadBalancer
  selector:
    app: jenkins-master
  ports:
    - port: 8080
      targetPort: 8080
  
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
  namespace: jenkins
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins-master